spring:
  kafka:
    bootstrap-servers: 192.168.0.25:9092
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      group-id: search
      auto-offset-reset: earliest
      max-poll-records: 1000
      auto-commit-interval: 1000
      enable-auto-commit: true